apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-db
  labels:
    app: deployment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
  strategy:
    type: Recreate
    spec:
      containers:
      - name: mysql
        imagePullPolicy: Always
        image: "mysql:5.7"
        ports:
        - containerPort: 3306
        args:
        - "--ignore-db-dir=lost+found"
        envFrom:
          - configMapRef:
              name: config-db
          - secretRef:
              name: secret-db
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
            subPath: mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim