kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: clarus-pv-claim
    labels:
       type: clarus-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
resources:
  requests:
    storage: 3Gi
   selector:
    matchLabels:
      type: aws-pv